# Generated by Django 3.1.4 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'exercise_questions',
                'managed': False,
            },
        ),
    ]
