# Generated by Django 3.1.4 on 2020-12-30 03:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePaper',
            fields=[
                ('exercise_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exercise_date', models.DateTimeField(default=datetime.datetime(2020, 12, 30, 3, 11, 1, 730015))),
                ('status', models.IntegerField(db_column='status', default=0)),
            ],
            options={
                'db_table': 'exercise_paper',
                'managed': False,
            },
        ),
    ]
