# Generated by Django 3.1.4 on 2021-01-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': False},
        ),
    ]
