# Generated by Django 3.1.4 on 2021-02-02 10:24

from django.db import migrations, models
import ingestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_paper_id', models.CharField(blank=True, max_length=100, null=True)),
                ('class_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_img_path', models.FileField(upload_to=ingestion.models.exam_paper_path)),
            ],
            options={
                'db_table': 'ingestion',
                'managed': False,
            },
        ),
    ]
