# Generated by Django 3.1.4 on 2020-12-23 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_auto_20201223_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
    ]
