# Generated by Django 3.1.4 on 2020-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20201223_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='class_name',
        ),
        migrations.AddField(
            model_name='topics',
            name='class_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
