# Generated by Django 3.1.4 on 2020-12-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201223_0556'),
        ('topics', '0003_auto_20201223_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
    ]
