# Generated by Django 3.1.4 on 2021-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topics_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topics',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
