# Generated by Django 3.1.4 on 2020-12-26 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('school_name', models.CharField(db_column='school_name', max_length=100)),
                ('school_rank', models.IntegerField()),
                ('school_add', models.CharField(db_column='school_add', max_length=100)),
                ('school_population', models.IntegerField()),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
