# Generated by Django 3.1.4 on 2020-12-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'managed': False},
        ),
    ]
