# Generated by Django 3.1.4 on 2020-12-30 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsBank',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_desc', models.TextField()),
                ('tags', models.CharField(max_length=45)),
                ('weightage', models.DecimalField(decimal_places=0, max_digits=10)),
                ('styles', models.CharField(choices=[('1', 'Multiple choices answer'), ('0', 'blank answer box')], default='1', max_length=10)),
            ],
            options={
                'db_table': 'questions_bank',
                'managed': False,
            },
        ),
    ]
